# Generated by Django 3.2.4 on 2021-08-12 16:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='News Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_hy',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='News Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='News Content'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Article title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Article title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Article title'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_en',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_hy',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_ru',
            field=models.SlugField(null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category title'),
        ),
    ]
