# Generated by Django 3.2.4 on 2021-08-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0003_auto_20210812_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
